### ISSUE TITLE
December 8, 2016 - meeting notes

### ISSUE THREAD

**Issue by cdransf** [805developershub/Meetups#1]
## 12/8 meetup notes

Hey all! Thanks again for making it out to the meetup last night. We'll be [meeting Wednesday next week](http://meetu.ps/e/Chpks/d3Q8x/a) and, per our discussion, here are some helpful links, books and tutorials:

📚 **git**

- [Github's git tutorial](https://try.github.io)
- [Pro Git book](https://git-scm.com/book)
- [Oh shit, git!](http://ohshitgit.com/)
- [Github guides](https://guides.github.com)
- [Git Real](https://courses.codeschool.com/courses/git-real)
- [Git documentation](https://git-scm.com/documentation)

🔧 **Tools**

- [HTML5 Boilerplate](https://html5boilerplate.com)

**Comment by smeads** [comment]
@cdransf this sounds great! Thanks for putting all these resources together!
